### ISSUE TITLE
生成器创建的新模块代码如何使用?

### ISSUE THREAD

**Issue by zhaorx** [uncarbon97/helio-cloud#32]
代码生成器生成的前端代码是请求到adminapi的7001服务的,那案例中的book接口应该如何被访问?
是参考oss接口使用facade转发么,但是生成器的代码使用方式文档写的是不是跟实际代码不对应?

**Comment by uncarbon97** [comment]
代码生成器的「脚手架架构」，选择「微服务」，会生成对应Facade接口
controller里面也会变成访问Facade

**Comment by zhaorx** [comment]
我印象选的是微服务,好吧,那应该是搞错了,我再试试
